- nombre: VSI IA Pro - Código Fuente + Licencia Comercial
  descripcion: Acceso de por vida al código fuente de VSI Pro. Total libertad para modificar, mejorar y distribuir comercialmente.
  enlace: https://pay.hotmart.com/B102592853U?off=y2m8474y
  color: turquesa
  icono: /assets/img/productos/producto-vsi-id-pro.png
  botonprod: Comprar VSI IA Pro →
