- nombre: VSI IA Pro - Código Fuente + Licencia Comercial
  descripcion: Acceso de por vida al código fuente de VSI Pro. Total libertad para modificar, mejorar y distribuir comercialmente.
  enlace: https://initnulltv.hotmart.host/vsi-ia-pro
  color: turquesa
  icono: /assets/img/productos/producto-vsi-id-pro.png
  botonprod: Comprar VSI IA Pro →
